# Generated by Django 5.0.4 on 2024-12-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("ref_name", models.CharField(max_length=20)),
                (
                    "prof_pic",
                    models.ImageField(
                        blank=True,
                        default="Profile_Pictures/defaultUser.jpeg",
                        upload_to="Profile_Pictures/",
                    ),
                ),
                ("bio", models.TextField(null=True)),
                ("skills", models.TextField()),
                ("github", models.CharField(max_length=150, null=True)),
                ("linkedin", models.CharField(max_length=150, null=True)),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
