# Generated by Django 5.0.4 on 2024-12-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="category",
            field=models.CharField(default="Web Development", max_length=150),
        ),
    ]
