# Generated by Django 5.0.4 on 2024-12-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="prof_pic",
            field=models.ImageField(
                blank=True,
                default="Profile_Pictures/defaultUser.jpg",
                upload_to="Profile_Pictures/",
            ),
        ),
    ]
