# Generated by Django 4.2 on 2024-12-27 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("project_pics", models.JSONField(blank=True, null=True)),
                (
                    "cover_pic",
                    models.ImageField(
                        blank=True,
                        default="Project_cover_Pictures/defaultProject.jpg",
                        null=True,
                        upload_to="Project_cover_Pictures/",
                    ),
                ),
                ("demo_link", models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("rating", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.projects"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("ref_name", models.CharField(max_length=20)),
                (
                    "prof_pic",
                    models.ImageField(
                        blank=True,
                        default="Profile_Pictures/defaultUser.jpg",
                        upload_to="Profile_Pictures/",
                    ),
                ),
                ("bio", models.TextField(null=True)),
                ("skills", models.TextField()),
                ("github", models.CharField(max_length=150, null=True)),
                ("linkedin", models.CharField(max_length=150, null=True)),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
